application: stage-5-final-project
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
  